# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b447f920666102a4e453a493504c5ad9d660650c5898f4d8e68a9ed1a830db3d883a020fd677a794632298950389628e409359b92ab91abc50acdfa936f7f65

test:
  secret_key_base: 8b89d02b77feae279291ad1a924b393f184f99cf1ba77fa0f61ed3e56eae03d450fd01df087fa779bae2bff781ce13eb66a595410dfc0520ccac32525b74001a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
